csv:
  encoding: Shift_JIS

google:
  worksheet: フォームの回答 1

corporations:
  sankoh:
    db:
      host: xxxx
      port: 5432
      user: user_sankoh_insert
      password: xxxx
      database: reservation_db_sankoh
    facilities:
      sankoh:
        facility_code: 1
        delete: false
        before_insert_sql: "DELETE FROM enquetes WHERE enquete_system_name = 'spreadsheet'"
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: sankoh
        facility_processors:
          facility_code:
            resolver: resolve_sankoh_facility_code
            required_headers: get_sankoh_required_headers

  a_and_c:
    db:
      host: xxxx
      port: 5432
      user: user_a_and_c_insert
      password: xxxx
      database: reservation_db_a_and_c
    facilities:
      kifunosato:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: 1Ixx
          worksheet: フォームの回答 1
        mapping_files: a_and_c_japanese
      roka_japanese:
        facility_code: 2
        delete: true
        before_insert_sql:
        spreadsheet:
          id: 1xx
          worksheet: フォームの回答 1
        mapping_files: a_and_c_japanese
      roka_english:
        facility_code: 2
        delete: false
        before_insert_sql:
        spreadsheet:
          id: xxx
          worksheet: フォームの回答 1
        mapping_files: a_and_c_english

  tachibanaya:
    db:
      host: xxxx
      port: 5432
      user: user_tachibanaya_insert
      password: xxxx
      database: reservation_db_tachibanaya
    facilities:
      tachibanaya:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: tachibanaya

  ginzansou:
    db:
      host: xxxx
      port: 5432
      user: user_ginzansou_insert
      password: xxxx
      database: reservation_db_ginzansou
    facilities:
      ginzansou:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: ginzansou

  sunshine:
    db:
      host: ixxx
      port: 5432
      user: user_sunshine_insert
      password: wxxx
      database: reservation_db_sunshine
    facilities:
      sunshine:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: sunshine
      tsuganoki:
        facility_code: 2
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: sunshine

  hachinobo:
    db:
      host: xxxx
      port: 5432
      user: user_hachinobo_insert
      password: xxxx
      database: reservation_db_hachinobo
    facilities:
      hachinobo:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: hachinobo
        facility_processors:
          facility_settings:
            provider: hachinobo_enquetes_settings
      hachinobo_text:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: hachinobo_text
        facility_processors:
          facility_settings:
            provider: hachinobo_text_settings

  goshobo:
    db:
      host: xxxx
      port: 5432
      user: user_goshobo_insert
      password: xxxx
      database: reservation_db_goshobo
    facilities:
      goshobo:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files:
        facility_processors:
          mapping:
            provider: goshobo_language_mapping_settings
            language_column: language
            language_mappings:
              日本語: goshobo_japanese
              english: goshobo_english
          value_conversions:
            provider: goshobo_room_number_conversions

  kanon:
    db:
      host: xxxx
      port: 5432
      user: user_kanon_insert
      password: xxxx
      database: reservation_db_kanon
    facilities:
      kanon:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: kanon
      fujiya:
        facility_code: 2
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: kanon
      kureha:
        facility_code: 3
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: kureha

  kinokuniya:
    db:
      host: xxxx
      port: 5432
      user: user_kinokuniya_insert
      password: xxxx
      database: reservation_db_kinokuniya
    facilities:
      kinokuniya:
        facility_code: 1
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: kinokuniya
      kino_hanare:
        facility_code: 2
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: kinokuniya
      kino_bettei:
        facility_code: 3
        delete: true
        before_insert_sql:
        spreadsheet:
          id: 1xxxx
          worksheet: フォームの回答 1
        mapping_files: kinokuniya
      oyadohiruta:
        facility_code: 4
        delete: true
        before_insert_sql:
        spreadsheet:
          id: 1xxxx
          worksheet: フォームの回答 1
        mapping_files: kinokuniya
      yuumi:
        facility_code: 5
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: kinokuniya
      sazane:
        facility_code: 6
        delete: true
        before_insert_sql:
        spreadsheet:
          id: 1xxxx
          worksheet: フォームの回答 1
        mapping_files: kinokuniya
      amane:
        facility_code: 7
        delete: true
        before_insert_sql:
        spreadsheet:
          id: 1xxxx
          worksheet: フォームの回答 1
        mapping_files: kinokuniya
      danqoo:
        facility_code: 8
        delete: true
        before_insert_sql:
        spreadsheet:
          id: xxxx
          worksheet: フォームの回答 1
        mapping_files: kinokuniya
