---
csv:
  encoding: Shift_JIS
google:
  worksheet: フォームの回答 1
corporations:
  a_and_c:
    db:
      host: incrazetech-app-db-prod.app-prod.incrazetech.dev
      port: 5432
      user: user_a_and_c_insert
      password: xxxxx
      database: reservation_db_test
    facilities:
      kifunosato:
        facility_code: 1
        delete: true
        spreadsheet:
          id: xxxxx
        mapping: japanese
      roka_japanese:
        facility_code: 2
        delete: true
        spreadsheet:
          id: xxxxx
        mapping: japanese
        enquete_key_suffix: ja
      roka_english:
        facility_code: 2
        delete: false
        spreadsheet:
          id: xxxxx
        mapping: english
        enquete_key_suffix: en
      sankoh:
        facility_code: 3
        delete: false
        before_insert_sql: DELETE FROM enquetes WHERE facility_code = 3 AND start_date >= CURRENT_DATE - INTERVAL '90 days'
        spreadsheet:
          id: xxxxx
        mapping_files:
          - facility_mappings/a_and_c/sankoh.yaml
        mapping: sankoh_japanese
        facility_code_processor: sankoh_facility_code
        facility_code_source: 宿泊施設
  goshobo:
    db:
      host: xxxxx
      port: 5432
      user: xxxxx
      password: xxxxx
      database: xxxxx
    facilities:
      goshobo:
        facility_code: 1
        delete: true
        spreadsheet:
          id: xxxxx
        mapping_files:
          - facility_mappings/goshobo/goshobo.yaml
        language_column: 言語 / Language
        language_mappings:
          日本語: goshobo_japanese
          English: goshobo_english
        value_conversion_processor: goshobo_room_number
  tachibanaya:
    db:
      host: incrazetech-app-db-prod.app-prod.incrazetech.dev
      port: 5432
      user: user_tachibanaya_insert
      password: xxxxx
      database: reservation_db_tachibanaya
    facilities:
      tachibanaya:
        facility_code: 1
        spreadsheet:
          id: xxxxx
        mapping: default
  ginzansou:
    db:
      host: incrazetech-app-db-prod.app-prod.incrazetech.dev
      port: 5432
      user: user_ginzansou_insert
      password: xxxxx
      database: reservation_db_ginzansou
    facilities:
      ginzansou:
        facility_code: 1
        spreadsheet:
          id: xxxxx
        mapping: default
  sunshine:
    db:
      host: incrazetech-app-db-prod.app-prod.incrazetech.dev
      port: 5432
      user: user_sunshine_insert
      password: xxxxx
      database: reservation_db_sunshine
    facilities:
      sunshine:
        facility_code: 1
        spreadsheet:
          id: xxxxx
        mapping: default
      tsuganoki:
        facility_code: 2
        spreadsheet:
          id: xxxxx
        mapping: default
  hachinobo:
    db:
      host: incrazetech-app-db-prod.app-prod.incrazetech.dev
      port: 5432
      user: user_hachinobo_insert
      password: xxxxx
      database: reservation_db_hachinobo
    facilities:
      hachinobo:
        facility_code: 1
        spreadsheet:
          id: xxxxx
          worksheet: enquetes
        mapping: enquetes
        table: enquetes
      hachinobo_text:
        facility_code: 1
        spreadsheet:
          id: xxxxx
          worksheet: enquetes_text
        mapping: enquetes_text
        table: enquetes_text
  kanon:
    db:
      host: incrazetech-app-db-prod.app-prod.incrazetech.dev
      port: 5432
      user: user_kanon_insert
      password: xxxxx
      database: reservation_db_kanon
    facilities:
      kanon:
        facility_code: 3
        spreadsheet:
          id: xxxxx
        mapping: kureha
  kinokuniya:
    db:
      host: incrazetech-app-db-prod.app-prod.incrazetech.dev
      port: 5432
      user: user_kinokuniya_insert
      password: xxxxx
      database: reservation_db_kinokuniya
    facilities:
      kinokuniya:
        facility_code: 1
        spreadsheet:
          id: xxxxx
        mapping: default
      kino_hanare:
        facility_code: 2
        spreadsheet:
          id: xxxxx
        mapping: default
      kino_bettei:
        facility_code: 3
        spreadsheet:
          id: xxxxx
        mapping: default
      oyadohiruta:
        facility_code: 4
        spreadsheet:
          id: xxxxx
        mapping: default
      yuumi:
        facility_code: 5
        spreadsheet:
          id: xxxxx
        mapping: default
      sazane:
        facility_code: 6
        spreadsheet:
          id: xxxxx
        mapping: default
      amane:
        facility_code: 7
        spreadsheet:
          id: xxxxx
        mapping: default
      danqoo:
        facility_code: 8
        spreadsheet:
          id: xxxxx
        mapping: default
      misasa:
        facility_code: 9
        spreadsheet:
          id: xxxxx
        mapping: default
